# This file is in YAML syntax (see http://www.yaml.org)
#
# The syntax is INDENTATION-SENSITIVE.  Mess it up at your peril!
#
language: java
jdk:
  - oraclejdk7
branches:
  except:
    - docs
before_install:
  - mvn -version
    #  - if [ $TRAVIS_BRANCH == "development" ] ; then { sudo apt-get update -qq; sudo apt-get install -qq nsis nsis-common nsis-pluginapi; } ; fi
install:
  - echo "-*- Precompile Core -*-"
  - mvn -B install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
    #  - echo "-*- Precompile IDE -*-"
    #- mvn -B install -f ide/pom.xml -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dgit-commit-id.skip=true
script: 
  - echo travis_fold:start:compile_core
  - mvn -B install -Dmaven.javadoc.skip=true
  - echo travis_fold:end:compile_core
    #- echo travis_fold:start:compile_ide
    #- mvn -B install -f ide/pom.xml -Dgit-commit-id.skip=true -Pall-platforms -P!ui-tests
    #- echo travis_fold:end:compile_ide
